minimax:
  api_key: >-
    sk-cp-7JJv6ZF3leWojiAZ5LTTN_wGSdbKeizdibhbhd-uAalq_-fEohpd3idcynO_guVifHigDpYO1wQyfaTQfzb_t45zHuDncqvdj4P5X5Le_pFWnDYbOHVgPzY
  group_id: ''
  vision_model: MiniMax-VL-01
  text_model: MiniMax-M2.5
feishu:
  webhook_url: ''
wechat:
  enabled: false
  window_title: 微信
wecom:
  enabled: true
  window_title: 企业微信
workflow_mode: assistant
mode: auto
escalation:
  keywords: 转人工
  max_unsolved_rounds: 5
reply_delay_min: 1
reply_delay_max: 3
ocr:
  enabled: true
  fast_mode: false
  check_interval: 20
  chat_region_mode: auto
  chat_region:
    - 0.35
    - 0
    - 1
    - 1
  languages:
    - zh-Hans
    - en
  trigger_keywords: 转人工
openclaw:
  customer:
    enabled: true
    cli_path: /opt/homebrew/bin/openclaw
    timeout_seconds: 120
    extra_prompt: ''
    routes:
      - enabled: true
        keywords: 任务收到
        agent_id: qinwu-yuan
        agent_name: 勤务猿
        extra_prompt: 根据上述对话信息，在飞书任务中创建任务。并最后给我返回任务名称
  assistant:
    enabled: true
    cli_path: /opt/homebrew/bin/openclaw
    timeout_seconds: 120
    extra_prompt: ''
    routes:
      - enabled: true
        keywords: 任务收到
        agent_id: qinwu-yuan
        agent_name: 勤务猿
        extra_prompt: 根据上述对话信息，在飞书任务中创建任务。并最后给我返回任务名称
      - enabled: true
        keywords: 收到低修任务
        agent_id: wenruan-niu
        agent_name: 稳如牛
        extra_prompt: |-
          提取上述对话信息中的待处理信息。格式：
          <线路名称>：<修改低消金额>
          然后使用mcp:dixiao-key-manager去处理
